# Generated by Django 3.1.4 on 2020-12-11 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0002_auto_20201211_0835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedWorkouts',
            new_name='SavedWorkout',
        ),
        migrations.RenameModel(
            old_name='TrackedAthletes',
            new_name='TrackedAthlete',
        ),
    ]
