# Generated by Django 3.1.4 on 2020-12-16 13:49

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20201216_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='workout',
            name='rests',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='workout',
            name='targets',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), blank=True, null=True, size=None),
        ),
    ]
