# Generated by Django 3.1.4 on 2020-12-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20201211_0836'),
        ('club', '0002_auto_20201211_0802'),
    ]

    operations = [
    ]
