# Generated by Django 3.1.4 on 2020-12-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20201216_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutresult',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to='club.workout'),
        ),
    ]
